import { c as create_ssr_component } from "../../chunks/ssr.js";
const _layout_svelte_svelte_type_style_lang = "";
const css = {
  code: "@font-face{font-family:'SF-Pro-Text-Bold';src:url('/static/fonts/SF-Pro-Text-Bold.otf');font-weight:bold;font-style:normal}@font-face{font-family:'SF-Pro-Text-Medium';src:url('/static/fonts/SF-Pro-Text-Medium.otf');font-weight:medium;font-style:normal}@font-face{font-family:'SF-Pro-Text-Regular';src:url('/static/fonts/SF-Pro-Text-Regular.otf');font-weight:normal;font-style:normal}.navbar-fixed.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{height:0px}nav.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{background-color:#1b263b;bottom:0px}ul.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{display:flex;justify-content:space-around;padding-left:0px}nav.svelte-1tgoxte ul.svelte-1tgoxte:not(.dropdown-content) a.svelte-1tgoxte:hover:not(.active){background-color:#0d1b2a}.sidenav.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{background:#0d1b2a}img.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{padding-right:10px}.nome.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{font-family:SFProText-Medium;font-size:18px;color:#ffffff;letter-spacing:1px}.lema.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{font-family:SFProText-Regular;font-size:14px;color:#e0e1dd;letter-spacing:1px}.titular.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{background-color:#e0e1dd;font-family:SFProText-Medium;font-size:14px;color:#0D1B2A;letter-spacing:1px;padding-left:10px;padding-top:20px;padding-bottom:20px;margin-top:40px}.cidades.svelte-1tgoxte.svelte-1tgoxte.svelte-1tgoxte{font-family:SFProText-Regular;font-size:14px;letter-spacing:1px}",
  map: null
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  $$result.css.add(css);
  return `<div class="navbar-fixed svelte-1tgoxte"><nav class="svelte-1tgoxte"><div class="nav-wrapper"><ul class="svelte-1tgoxte"><li data-svelte-h="svelte-xcjdj6"><a href="/" class="svelte-1tgoxte"><img src="./IconHome.svg" class="svelte-1tgoxte"></a></li> <li><a class="svelte-1tgoxte" data-svelte-h="svelte-1ew4yrq"><img src="./IconCidades.svg" class="svelte-1tgoxte"></a></li> <li data-svelte-h="svelte-1alj4rb"><a href="/buscar" class="svelte-1tgoxte"><img src="./IconBuscar.svg" class="svelte-1tgoxte"></a></li> <li data-svelte-h="svelte-19e3l6q"><a href="/configuracion" class="svelte-1tgoxte"><img src="./IconConfig.svg" class="svelte-1tgoxte"></a></li></ul></div></nav></div> <ul id="slide-out" class="sidenav svelte-1tgoxte" data-svelte-h="svelte-1yd1kh9"><div><li><div class="user-view center"><a href="#user" class="svelte-1tgoxte"><img src="GaliciaWeather.gif" width="70%" class="svelte-1tgoxte"></a> <p class="white-text nome svelte-1tgoxte">GaliciaWeather Plus</p> <p class="white-text lema svelte-1tgoxte">O tempo de Galicia</p></div></li> <li class="titular svelte-1tgoxte">Escolle unha cidade galega:</li> <li><a class="cidades white-text svelte-1tgoxte" href="/santiago"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte"> Santiago de Compostela</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/coruna"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">A Coruña</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/ferrol"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Ferrol</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/vigo"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Vigo</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/lugo"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Lugo</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/vilagarcia"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Vilagarcía de Arousa</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/ourense"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Ourense</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/pontevedra"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Pontevedra</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/sanxenxo"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Sanxenxo</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/monforte"><img src="flecha_der.png" alt="flecha" class="svelte-1tgoxte">Monforte</a></li> <li><div class="divider"></div></li> <li><a class="cidades white-text svelte-1tgoxte" href="/configuracion">Créditos</a></li> <li><a class="cidades white-text svelte-1tgoxte" href="/privacidade">Política de privacidade</a></li></div></ul> ${slots.default ? slots.default({}) : ``}`;
});
export {
  Layout as default
};
